FROM node:16-alpine AS dev

WORKDIR /app

COPY docker/app/bashrc /root/.bashrc
COPY docker/app/starship.toml /root/.config/
RUN apk update && \
    apk upgrade && \
    apk add --no-cache ca-certificates openssh-client git vim bash && \
    git config --global color.ui true && \
    git config --global core.pager more && \
    git config --global pull.rebase true && \
    git config --global fetch.prune true && \
    git config --global diff.colorMoved zebra && \
    apk add --no-cache --virtual .install-deps curl && \
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes && \
    sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd  && \
    apk del .install-deps && \
    rm -rf /var/cache/*/*

COPY package*.json yarn.lock ./
RUN yarn install

ENV NODE_ENV development
ENV EDITOR /usr/bin/vim
ENV LC_ALL en_US.UTF-8

CMD ["yarn" , "dev"]
