services:
  app.dev:
    env_file:
      - .env
    user: "node:node"
    restart: always
    environment:
      BOT: droblox
      NODE_ENV: production
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
