services:
  app.dev:
    env_file:
      - .env
    user: "node:node"
    restart: always
    environment:
      NODE_ENV: development
    build:
      context: .
      dockerfile: docker/app/Dockerfile.app.dev
    volumes:
      - .:/home/node/app
      - dev-node_modules:/home/node/app/node_modules

volumes:
  dev-node_modules:
